node {
   def commit_id
   stage('preparation') {
     checkout scm
     //sh "git rev-parse --short HEAD > .git/commit-id"
     //commit_id = readFile('.git/commit-id').trim()
     commit_id = bat(returnStdout: true, script: 'git rev-parse --short HEAD')
     commit_id = commit_id.substring(commit_id.lastIndexOf(" ") + 1, commit_id.length()).trim()
     echo "CommitID: ${commit_id} ---"
   }

   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       bat 'npm install --only=dev'
       bat 'npm test'
     }
   }

   def app
   stage('docker build image') {
     app = docker.build("andreimihai24/docker-nodejs-example:${commit_id}", '.')
   }

   stage('docker push image') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       app.push()
     }
   }
}
