node {
   def commit_id
   stage('preparation') {
     checkout scm
     commit_id = bat(returnStdout: true, script: 'git rev-parse --short HEAD')
     commit_id = commit_id.substring(commit_id.lastIndexOf(" ") + 1, commit_id.length()).trim()
     echo "CommitID:${commit_id}---"
   }

   stage('test') {
     def myTestContainer = docker.image('node:4.6')
     myTestContainer.pull()
     myTestContainer.inside {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }

   stage('test with a DB') {
     def mysql = docker.image('mysql').run("-e MYSQL_ALLOW_EMPTY_PASSWORD=yes") 
     def myTestContainer = docker.image('node:4.6')
     myTestContainer.pull()
     myTestContainer.inside("--link ${mysql.id}:mysql") { // using linking, mysql will be available at host: mysql, port: 3306
          sh 'npm install --only=dev' 
          sh 'npm test'                     
     }                                   
     mysql.stop()
   }

   def app
   stage('docker build image') {
     app = docker.build("andreimihai24/docker-nodejs-example:${commit_id}", '.')
   }

   stage('docker push image') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       app.push()
     }
   }
}                                          
